# Input
input: "examples/fastqs/*_R{1,2}_concatenated.fastq.gz"
project: 'test_run_with_concat'
outdir: 'test/output'
ots28_missing_threshold: 0.7
pofz_threshold: 0.8
trim_params: "LEADING:15 TRAILING:15 SLIDINGWINDOW:4:15 MINLEN:36"
gsi_missing_threshold: 0.6
max_overlap: 400
locus_index: 'data/indices/transition_loci_indices_20241104.csv'
baseline: 'data/baselines/full/SWFSC-chinook-reference-baseline-CV.csv'
panel: 'full'
input_format: "auto"
min_overlap: 3
adapter_file: "data/adapters/GTseq-PE.fa"
ots28_baseline: "data/baselines/full/RoSA_baseline_partial_infile.txt"
n_loci: 204
rubias_show_missing_data: "TRUE"

concat_all_reads: false
run_fastqc: false
run_dimer_check: true
use_CKMR: FALSE
CKMR_logl_threshold: 6.9
CKMR_min_loci: 90
CKMR_parent_geno_input: "examples/PBT/FRH2024_reference_genotypes.csv"
use_sequoia: FALSE
sequoia_mode: "ped"
sequoia_missing_threshold: 0.5
parent_geno_input: "examples/PBT/FRH2024_reference_genotypes.csv"
parent_lifehistory: "examples/PBT/FRH2024_reference_lifehistory.txt"
offspring_birthyear: "unknown"
offspring_minBY: "unknown"
offspring_maxBY: 2025
offspring_max_age: 8
species_min_repro_age: 1
species_max_repro_age: 8
